import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Image from "next/image";
import logo from "@/../public/logo_img.jpg";
// import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function Navbar() {
  return (
    <div className="h-[90px] bg-(--background-red) text-(--foreground-white) px-24 p-3 flex flex-row justify-between">
      <Image src={logo} alt="S.U.E. Logo" width={64} height={64} className="rounded-full"/>
      <div className="flex flex-row justify-evenly w-1/2">
        <div className="flex flex-row items-center w-4/5">
          <p className="mx-5">HOME</p>
          <p className="mx-5">ABOUT CENTER</p>
          <p className="mx-5">COURSES</p>
          <p className="mx-5">FAQS</p>
          <p className="mx-5">BLOGS</p>
        </div>
        <button className="border-2 w-24 h-1/2 mt-4 rounded-lg">Login</button>
      </div>
    </div>
  )
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
